/* This file was generated by hand. Do not edit! */

#ifndef __org_lwjgl_BufferUtils_h_
#define __org_lwjgl_BufferUtils_h_

#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_org_lwjgl_BufferUtils_zeroBuffer0
  (JNIEnv *env, jclass clazz, jobject buffer, jlong offset, jlong size);

JNIEXPORT jlong JNICALL Java_org_lwjgl_BufferUtils_getBufferAddress
  (JNIEnv *env, jclass clazz, jobject buffer);

#ifdef __cplusplus
}
#endif

#endif // __org_lwjgl_BufferUtils_h_
